name: amd_group_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  gallery_saver: ^2.3.2
  get_it: ^7.6.4
  hydrated_bloc: ^9.1.2
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
